### ISSUE TITLE
Add new proposal action support

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#1045]
- [x] UI design (@Popoulosss )
- [x] Implement new proposal action

**Comment by Popoulosss** [comment]
Refer to [new proposal process in subsquare](https://www.figma.com/file/FHG6vk7A6jzBM5wQ8CMdkX/SubSquare?node-id=6652%3A73060)

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=4077%3A23520)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/194741471-197ccaf2-8be8-4cf8-b912-ad30e679c1c6.png">
