### ISSUE TITLE
As a user, I want to see the expenses through gov2

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1071]
1. The expense will be decided by different gov2 referenda tracks
2. Statistics by different tracks
3. I can see the list by different tracks

Appendix: treasury related tracks:
- `Treasury`: Spending (any amount of) funds
- `Small Tipper`: Able to spend up to 1 KSM from the treasury at once
- `Big Tipper`: Able to spend up to 5 KSM from the treasury at once
- `Small Spender`: Able to spend up to 50 KSM from the treasury at once
- `Medium Spender`: Able to spend up to 500 KSM from the treasury at once
- `Big Spender`: Able to spend up to 5,000 KSM from the treasury at once

**Comment by Popoulosss** [comment]
1. As a community member, I want to filter current treasury applications by different referenda tracks.

**Comment by Popoulosss** [comment]
1. As a community member, I want to filter current treasury applications by different referenda tracks.

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/206989755-06a782a6-1c8b-4dd1-9f88-e07e8e0d61ea.png">
