### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1099]
full pr: #1116 

Home page:
1. Show current available treasury fiat value.
2. Show the spend period whole period length.
3. Show current gov2 application status, like ongoing/all.
4. Show gov2 treasury spend distribution with a pie chart. Each item should show the amount and treasury proposal amount.
5. Ratio of Gov1 proposals pending/approved/rejected number.
6. Ratio of Gov2 proposals pending/approved/rejected number.

**Comment by wliyongfeng** [comment]
On each sections:
1. We should show total funded amount in token and fiat value.
2. We should show the values proposed or under review/discussion/voting.

**Comment by Popoulosss** [comment]
- [ ] Modify the layout
- [ ] Add 'To be awarded' and 'OpenGov' to data card
- [ ] Display current fiat value of 'Avaliable', 'To be awarded'
- [ ] Display the spend period whole period length
- [ ] Change icons size to 60px

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=4859%3A29387&t=Hhviyiam6VxQntYC-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/216064672-1e11b620-229c-4e38-86c0-5a4eaa0d7fe9.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/216065096-e4bd3d28-4964-4a9a-84a8-26724dbbec45.png">

**Comment by Popoulosss** [comment]
- [ ] Add ‘OpenGov Spend’ card
- [ ] Modify the layout
- [ ] Display OpenGov treasury spend amount(section) and fiat value (area) by coxcomb chart

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=4859%3A29387&t=Hhviyiam6VxQntYC-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/216065786-f95a1202-4be3-4589-978b-1778673f9c88.png">

**Comment by Popoulosss** [comment]
- [ ] Display the fiat value of output
- [ ] Add OpenGov spend amount and fiat value to output of proposals

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=4859%3A29387&t=Hhviyiam6VxQntYC-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/216067496-802d2bc9-3864-4988-8d11-9e579b4f24ba.png">

**Comment by Popoulosss** [comment]
- [ ] Change the font size of 'Total Stacked'
- [ ] Modify the layout

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=4859%3A29387&t=Hhviyiam6VxQntYC-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/216067933-ddda123a-4211-4c20-bf14-b8a06c5d0de6.png">

**Comment by Popoulosss** [comment]
- [ ] Modify the data cell layout

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/216068829-dbaa8980-9c8d-4d33-a342-4647cd2336a5.png">
