### ISSUE TITLE
Add track types to OpenGov treasury applications

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/dotreasury#1140]
- Add track types to OpenGov proposals

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=4404%3A25093&t=zLlYXYpHXjZ10emv-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/222060762-b3beadad-afd8-46b7-b071-c8256f245deb.png">

**Comment by Popoulosss** [comment]
- [ ] Change the subtitle from 'Gov1 Applications' to 'OpenGov Applications'

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/222061214-1838da91-95cb-4035-9580-0caff4f71dc1.png">

**Comment by Popoulosss** [comment]
- [ ] Fix the subtitle bar's layout

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=4404%3A25093&t=zLlYXYpHXjZ10emv-11)

Preview
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/59445675/222061612-92ec63f5-ff11-47fd-978c-2812dfe8586b.png">

**Comment by 2nthony** [comment]
proposals list

![img_v2_0bbfe193-345b-49ae-8d4c-f2ac7e60e47g](https://user-images.githubusercontent.com/19513289/223604093-3b652c30-aee2-49b8-8ab3-eca8af743061.jpg)
