### ISSUE TITLE
fix proposals list summary layout

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/dotreasury#1142]
viewport less than 1200

![image](https://user-images.githubusercontent.com/19513289/223603880-01f582b9-0d90-4adc-891c-425cb3bb87a8.png)

less than 1160

![image](https://user-images.githubusercontent.com/19513289/223604020-d13c8a93-298f-4829-a9ed-706c2cbfe5d5.png)

**Comment by Popoulosss** [comment]
- Optimize ui styles (subtitle's font size, font color, panel layout, refer to homepage data panel)
- Remove the divider after the ''Ongoing' cell in applications summary
- Hide the countdown chart of spend period
- Add currency value to 'Available' in proposals list sumamry (refer to homepage data panel)
- Add total period time to 'Spend period' in proposals list sumamry (refer to homepage data panel)

[Figmal link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=5088-30734&t=4Z5Z3ygg6DwEYox8-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/223675264-1e4b0484-3f58-489d-812c-ca5d5f7747d7.png">
