### ISSUE TITLE
theme: light/dark (css3 var)

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/dotreasury#1155]
full pr: #1167 

- [x] move current colors to `light.js`
- [x] `dark.js`
- [x] vars: light and dark
- [x] css vars to `:root`, good for `tailwindcss.js`
- [x] ?switch theme button([updated](https://github.com/opensquare-network/dotreasury/issues/1155#issuecomment-1514123577))
   - [x] system, hooks from `usehooks-ts`
   - [x] light
   - [x] dark
- [x] persist theme setting (`useLocalStorage`
- [ ] bulk of code to refactor
   - [x] remove all colours in `constants/index.js`
   - [x] panels background color
   - [x] `TextMajor, TextMinor` color
   - [x] header bgc
- [x] remove `styled.ThemeProvider`(we use css3 variables for better DX #1163
- [ ] icons
- [x] `totalStacked` chart color
- [x] type friendly hook `useTheme`
- [x] no flash, copy some to `html` is find ~~move `theme.index.js` as `xxx/index.css` (way to avoid flicker, js is slow to set global css vars~~
- [x] footer logos
- [ ] table
   - [x] loading mask
   - [x] left expand icon button
   - [x] sub-table
- [ ] chart
   - [x] burn
- [ ] detail
   - [x] rating
   - [x] comment
- [ ] user detail
   - [x] link button
   - [x] heatmap color
- [x] connect wallet modal
- [x] account select
- [x] tooltip (from semantic
- [x] timeline
   - [x] expand button
   - [x] icons

**Comment by Popoulosss** [comment]
[Preview Version](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=5250-35347&t=bHyW47U8FOSJ34KD-11)

<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/231338033-1bc24c72-df4f-4b18-b9a9-87963f9c0efd.png">

**Comment by Popoulosss** [comment]
Switch theme button refer to statescan

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2695-20902&t=tmUH5U4dTvP4o6QV-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/232969210-6672ef43-9843-4822-a89f-80be13ecd833.png">

**Comment by Popoulosss** [comment]
Files

Icons
[Icons.zip](https://github.com/opensquare-network/dotreasury/files/11268434/Icons.zip)

Footer logo
[footer logo.zip](https://github.com/opensquare-network/dotreasury/files/11302981/footer.logo.zip)

Data panel icons
[data panel icons.zip](https://github.com/opensquare-network/dotreasury/files/11303134/data.panel.icons.zip)
