### ISSUE TITLE
Disable new proposal/tip for kusama

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1205]
Treasury proposals and tips should now go through OpenGov. We should disable buttons with hint about OpenGov.

![rNVLLynxYZ](https://user-images.githubusercontent.com/2264908/236402928-f385acf9-62c3-46d4-896f-6f8d446db085.jpg)

**Comment by Popoulosss** [comment]
OpenGov applicaiton
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/236726283-a7bb9252-6759-414b-b6d6-46cab1d14784.png">

Proposals (disabled)
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/236726629-b9b51fee-45f4-404b-9773-1fa638c73c35.png">

Tips (disabled)
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/236726648-bad11bf5-f419-41e1-94f2-ecd4adb4d5f4.png">
