### ISSUE TITLE
Show the brief status stats in opengov applications

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/dotreasury#1260]
Under Voting
- submitted + queueing + deciding + confirming

Passing
- aye > nay

Approved
- approved (including historical data)

Rejected
- rejected (including historical data)

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?type=design&node-id=5206-46177&mode=design&t=hKQeCfoBILclztGg-11)

Web
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/f5975cbc-4fc8-428b-96ce-b91617d6bbd7">

Mobile
<img width="320" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/5f525cd7-2245-4b4b-8241-7d59653b8536">

**Comment by wliyongfeng** [comment]
`Under Voting` -> `Voting`

**Comment by Popoulosss** [comment]
Updated
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/ac3af63d-dcf6-4a45-8427-dd71319bdd14">
<img width="320" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/8926d5cc-a99e-47ae-8173-b05cb99dc951">
