### ISSUE TITLE
Zoom in&out for treasury mountain chart

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1264]
![hewgfqpFDF](https://github.com/opensquare-network/dotreasury/assets/2264908/19b89086-9854-459f-934a-9cf1c736d039)

**Comment by Popoulosss** [comment]
Refer to time shaft in subsquare > [statistics](https://kusama.subsquare.io/referenda/track/0/statistics)

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?type=design&node-id=6001-42218&mode=design&t=0d6pshwyI684P5pP-11)

Preview
Light
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/798a9d84-66aa-45b6-bb53-bf7e6ed71c27">
Dark
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/a8a56437-99cf-47cc-ae61-f986fc561340">
