### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/dotreasury#1292]
[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?type=design&node-id=6278-38567&mode=design&t=3IIgK2wNdbGkMcMH-11)

---

- [x] Header
   - [x] Contact Us -> `mailto:yongfeng@opensquare.network`
   - [x] Explore Treasury

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/14443ba5-31a8-4192-b210-5f2942d04076">

---

- [x] Hero
   - [x] Show the number of treasuries (dotreasury supported)
   - [x] Show the total of treasury assets
   - [x] Show the bubble chart
      - [x] The size of the bubble is determined by the proportion of the treasury amount

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/994c633c-60ce-402e-9935-7c624bb338b1">

---

- [x] Dotsama eco
   - [x] Bar chart
      - [x] Show the treasury fiat money and assets
   - [x] Pie chart
      - [x] Show the proportion of all treasuries in dotsama eco

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/720bac39-9db5-4375-97d3-bc36653d6713">

---

- [x] Dotsama treasury overview
   - [x] Show the treasury overview data
      - [x] Avaliable assets, spend Period, total income, total output, block height
      - [x] Total stacked chart (all time)
      - [x] Income and output distribution
      - [x] Top beneficiaries
   - [x] Supports switching between polkadot and kusama

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/36b70ce1-3f86-4db8-bb7e-72d5824307f2">

**Comment by Popoulosss** [comment]
- [ ] Moblile layout

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?type=design&node-id=6280-40391&mode=design&t=FOO4RkT6JDA2wrT2-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/7c933b8c-a9c3-4396-99a2-f644feb7267f">

**Comment by 2nthony** [comment]
bubble code, keyword `bubble-project`
https://github.com/Koniverse/DotInsights/blob/master/src/assets/scss/blocks/_bubbles.scss

**Comment by Popoulosss** [comment]
**Treasury icons**

Files
[treasury icons.zip](https://github.com/opensquare-network/dotreasury/files/12606456/treasury.icons.zip)

**Comment by Popoulosss** [comment]
## UI review

---
