### ISSUE TITLE
Implement dotreasury for centrifuge

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1323]
- Income
    - Pallet_elections_phragmen
    - ORML:tokens:OnDust
    - Democracy Slash
    - Identity Slash
    - Treasury Slash
    - Pallet_fees -> Treasury
    - pallet_block_rewards:Beneficiary

**Comment by Popoulosss** [comment]
## Centrifuge

- [ ] [Overview](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?type=design&node-id=6644-29549&mode=design&t=fmY6pXo3iQaHyfbw-11)
- [ ] [Income](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?type=design&node-id=6657-55733&mode=design&t=fmY6pXo3iQaHyfbw-11)
   - [ ] Block Rewards/Slashes(Treasury, Democracy, Identity, Election)/Gas Fee/Others
- [ ] [Users](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?type=design&node-id=6658-61303&mode=design&t=fmY6pXo3iQaHyfbw-11)
- [ ] [Proposal](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?type=design&node-id=6658-61299&mode=design&t=fmY6pXo3iQaHyfbw-11)
   - [ ] Proposal list
   - [ ] Proposal detail

Files
[logo-centrifuge.zip](https://github.com/opensquare-network/dotreasury/files/13010725/logo-centrifuge.zip)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/9a051e83-f764-441a-b507-429fb12147a7">

**Comment by Popoulosss** [comment]
- [ ] Add item to the dropdown menu in treasury homepage
- [ ] `Centrifuge` item clickable

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?type=design&node-id=6280-40146&mode=design&t=neqVI6et4MlS047f-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/756d528e-07f7-4d80-a249-6e4d7409c4d6">
<img width="320" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/ba97bffa-da30-4441-8198-bf001a2f88b5">
