### ISSUE TITLE
Add new project to landing page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1342]

**Comment by Popoulosss** [comment]
File
[treasury icons.zip](https://github.com/opensquare-network/dotreasury/files/13388560/treasury.icons.zip)

Add Pie chart color
- #9E4ADF
- #CA95F4

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/c9903633-1d2d-4e6e-9f71-c231d5582d27">

**Comment by Popoulosss** [comment]
- [ ] Biforst

- [ ] Add Pie chart color
   - [ ] Light: #79CA47, #AFE48D

File
[treasury icons 2.zip](https://github.com/opensquare-network/dotreasury/files/13624047/treasury.icons.2.zip)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/b1164f97-2889-486f-93e1-1607b6cc6779">
