### ISSUE TITLE
Treasury history fiat value chart

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1347]
- Red line is amount in DOT
- Green line is fiat value.

![telegram-cloud-photo-size-1-5157159419665033982-y](https://github.com/opensquare-network/dotreasury/assets/2264908/34c7d7cc-f0d4-4078-b317-bcf3d17303e8)

**Comment by Popoulosss** [comment]
[Figmal link](https://www.figma.com/design/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?node-id=7085-34543&t=c8wGyVWuRVhxekip-11)

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/72e2edaf-5647-4f89-b93e-660d5756200a">
