### ISSUE TITLE
Why Edgeware got removed?

### ISSUE THREAD

**Issue by ShankarWarang** [opensquare-network/dotreasury#1355]

**Comment by ShankarWarang** [comment]
https://github.com/opensquare-network/dotreasury/pull/1324/commits/b5ead47cb772084404b9f0caf334c22facf53ece

Reference: https://gov.edgewa.re/discussion/2069-proposal-dashboard-for-edgeware-treasury

**Comment by wliyongfeng** [comment]
Edgeware stop funding the maintenance. The code repo for edgtreasury is [here](https://github.com/opensquare-network/edgtreasury).
