### ISSUE TITLE
Remove polkascan and add statescan explorer link

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1382]
![kJiZZMBYwI](https://github.com/opensquare-network/dotreasury/assets/2264908/94b6a502-13ff-4745-a31c-a602452bdbf4)

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?node-id=5352-37742&t=KbnrNrEL4dEAvgOk-11)

Preview
<img width="320" alt="image" src="https://github.com/opensquare-network/dotreasury/assets/59445675/9f57c800-c838-409b-8325-64e42da31db4">
