### ISSUE TITLE
Add astar on landing page

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#1484]
@Popoulosss We need design stuff.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/design/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury-v2.0?node-id=6278-38567&t=3CTcsPRo3LW2EZcC-11)

Files
[logo-astar.zip](https://github.com/user-attachments/files/18159031/logo-astar.zip)

Color(pie chart)
- Light: #27D8A3
- Dark: #219371
