### ISSUE TITLE
Create a pm2 task to execute the links sync job every 3 minutes

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#254]
The sync script is [here](https://github.com/opensquare-network/dotreasury/blob/main/packages/server/src/migration/index.js)

**Comment by hyifeng** [comment]
Run shell commands:

```
$ pm2 start ./src/migration/index.js --cron "*/3 * * * *" --name link-migration
$ pm2 save
```

Then will execute migration every 3 minutes.
