### ISSUE TITLE
The proposal's treasury link is not updated in time

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#465]
When we exploring proposals, sometimes see that the treasury link is still linking to the previous opened proposal, and then update in a few seconds.

![image](https://user-images.githubusercontent.com/6297057/109129526-b2de3a80-778b-11eb-86ce-ae4d7548ca9e.png)

**Comment by wliyongfeng** [comment]
Maybe caused by #467

**Comment by hyifeng** [comment]
Please fix this problem on branch "release-1.0.5"
