### ISSUE TITLE
Reset the order of slashes

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#481]
The order should be:
1. Staking
2. Treasury
3. Election
4. Democracy
5. Identity

![Lark20210227-142635](https://user-images.githubusercontent.com/2264908/109377685-e2b24d00-7907-11eb-9519-90e312ce2590.png)
![Lark20210227-142700](https://user-images.githubusercontent.com/2264908/109377687-e5ad3d80-7907-11eb-8884-5b760a8265c8.png)

**Comment by mtwn105** [comment]
Hi @wliyongfeng 

I would like to contribute to this issue

Please can you provide more details about this?

**Comment by wliyongfeng** [comment]
> Hi @wliyongfeng
> 
> I would like to contribute to this issue
> 
> Please can you provide more details about this?

Thanks, but we solved this issue.
