### ISSUE TITLE
Chain info cover up by menu on mobile view

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#498]
![image](https://user-images.githubusercontent.com/6297057/109484549-87c15700-7abb-11eb-9a9f-37a1c43e9e13.png)

**Comment by wliyongfeng** [comment]
Add a menu icon for responsive

<img width="789" alt="Lark20210301-183428" src="https://user-images.githubusercontent.com/2264908/109485589-d3283500-7abc-11eb-989b-b36e80b3f711.png">
