### ISSUE TITLE
Add a filter component to Tips and Proposals List

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#509]
Add a filter to tips and proposals list to allow filtering items by status 

Tip filters: Closed, Tipping, Retracted
Proposal filters: Awarded...

![image](https://user-images.githubusercontent.com/6297057/109744620-961f8800-7c0d-11eb-8bae-e85a00cf22f9.png)

**Comment by Popoulosss** [comment]
Figma updated.

**Comment by hyifeng** [comment]
![image](https://user-images.githubusercontent.com/6297057/110056086-1aeadd00-7d99-11eb-9183-3fcce45fef7c.png)

Content overlap on mobile view
