### ISSUE TITLE
Disable the button when signup or login is in process

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#516]
![Lark20210303-160349](https://user-images.githubusercontent.com/2264908/109773402-1f4cb400-7c3a-11eb-95be-80ad31d9983d.png)
![Lark20210303-160408](https://user-images.githubusercontent.com/2264908/109773407-207de100-7c3a-11eb-8e08-0deba5e9d3ac.png)

**Comment by Popoulosss** [comment]
Figma updated.
