### ISSUE TITLE
Very neat UI, but some text is ambiguous

### ISSUE THREAD

**Issue by chrisli30** [opensquare-network/dotreasury#620]
The UI works smoothly. I like it, but what do "Income" and "Output" mean? Income means token supply, and output means token usage(or consumption)?

![image](https://user-images.githubusercontent.com/2616844/119073995-1484fe00-b9a3-11eb-8ac1-3c2c08e6607e.png)

I think you might need a question mark next to the text for explanation.

**Comment by wliyongfeng** [comment]
"Income" means where the treasury balance comes from, while "Output" means how the treasury assets are spent.

Yeah, we need more time to polish the text and I accept the suggestion for question mark and explanation.

**Comment by chrisli30** [comment]
Thanks for clarifying!

**Comment by wliyongfeng** [comment]
We should add external links for [income](https://wiki.polkadot.network/docs/learn-treasury#funding-the-treasury) and [output](https://wiki.polkadot.network/docs/learn-treasury#creating-a-treasury-proposal). @Popoulosss

**Comment by Popoulosss** [comment]
-  link to [Income](https://wiki.polkadot.network/docs/learn-treasury#funding-the-treasury)
-  link to [Outcome](https://wiki.polkadot.network/docs/learn-treasury#creating-a-treasury-proposal)

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2006%3A21476&t=PYEdjUe0YenzrIhC-11)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/212599987-232755f6-ac48-4796-a2ab-bfdb27008e14.png">
