### ISSUE TITLE
Inconsitent `@polkadot/api` and `@polkadot/util` version

### ISSUE THREAD

**Issue by chenzongxiong** [opensquare-network/dotreasury#624]
[“@polkadot/api": "^4.8.1”](https://github.com/opensquare-network/dotreasury/blob/main/packages/block-scan/package.json#L12)
["@polkadot/util": "^6.3.1",](https://github.com/opensquare-network/dotreasury/blob/main/packages/block-scan/package.json#L13)

["@polkadot/api": "^4.10.1"](https://github.com/opensquare-network/dotreasury/blob/main/packages/scan/package.json#L24)
["@polkadot/util": "^6.4.1"](https://github.com/opensquare-network/dotreasury/blob/main/packages/scan/package.json#L26)

**Comment by wliyongfeng** [comment]
Fixed.
