### ISSUE TITLE
Is there editing option for Tips, Proposal or Comments?

### ISSUE THREAD

**Issue by ccris02** [opensquare-network/dotreasury#647]
I was just looking at one of my Tips and I just wanted to change some information. Is there any editing button to modify something that I have submitted or Commented on?

**Comment by wliyongfeng** [comment]
No, you can't change onchain info. For comments on dotreasury, currently you can not edit the comment too, just leave new comments.

**Comment by ccris02** [comment]
There is 2 part for submitting tips:
1. Submit a tip on-chain (This cannot be changed, if I make mistake I have to close the tip and reopen it)
2. Add additional info on https://kusama.polkassembly.io/ (This is what I can change, modify, correct, it is not on-chain)
Are the comments that I add to https://www.dotreasury.com/ on-chain? 
In the 2nd part of the Tip, there is always some changes and addition. Maybe you misspelled or you want to add something.

**Comment by wliyongfeng** [comment]
> Submit a tip on-chain (This cannot be changed, if I make mistake I have to close the tip and reopen it)

No, you can not change it.

> Are the comments that I add to https://www.dotreasury.com/ on-chain?

No, currently anything edit on dotreasury will not on-chain.

> In the 2nd part of the Tip, there is always some changes and addition. Maybe you misspelled or you want to add something.

I think tip is for small expense. If you really want to change something, maybe just close the tip and open a new one, or add additional info to corresponding polkassembly tip page.

**Comment by ccris02** [comment]
Since the comments are not on-chain I think it would be good if whoever submits it be able to edit them. https://kusama.polkassembly.io/ has editing.
That's' just me.

**Comment by wliyongfeng** [comment]
We don't have to follow polkassembly, but let's see their feedbacks when there are more users. Actually currently there are seldom user who leave comments, let's keep it now.

**Comment by wliyongfeng** [comment]
I will close this issue. It will become invalid because of the direction of dotreasury. Dotreasury will be web3 oriented and a dapp including dashboard and statistics information. See #894 .
