### ISSUE TITLE
Treasury is not updating, its at least 12hr behind.

### ISSUE THREAD

**Issue by ccris02** [opensquare-network/dotreasury#648]
I see one of the Tips has all 10 Councils signed but on dotreasury.com it only has 8 Councils signed.
![image](https://user-images.githubusercontent.com/66147586/124051361-36759580-d9d1-11eb-888d-1007a6db9c7a.png)
![image](https://user-images.githubusercontent.com/66147586/124051418-59a04500-d9d1-11eb-9ac5-c3dd633f3db4.png)

**Comment by wliyongfeng** [comment]
Thanks for report @ccris02 . It's due to our polkadot node is old(0.8.30), and has a error to import block. Now fixed.
