### ISSUE TITLE
Replace the footer logo

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#677]
![Lark20210809-114735](https://user-images.githubusercontent.com/2264908/128658802-684b24f2-02bb-47ba-96f1-f720e02dd5d3.png)
 @Popoulosss

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=125%3A9017

files
[logo-opensquare-v2.zip](https://github.com/opensquare-network/dotreasury/files/6952403/logo-opensquare-v2.zip)

preview
![image](https://user-images.githubusercontent.com/59445675/128665320-e5965457-7731-457e-b425-b1a138aab6b5.png)
