### ISSUE TITLE
As a user, I want a bar chart for burnt records to show the trend 

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#679]
An example, but we only need the upper part.

![Lark20210811-113701](https://user-images.githubusercontent.com/2264908/128965812-8c938f54-d571-44db-b60a-cdad9c181da3.png)

- [x] Design @Popoulosss 
- [x] API @hyifeng 
- [x] Fronted implementation @qiyisi

**Comment by Popoulosss** [comment]
figma link
https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=139%3A6950

preview
![image](https://user-images.githubusercontent.com/59445675/128987698-8012626b-cced-4d39-b09f-dc1380259bca.png)
