### ISSUE TITLE
Replace the OpenSquare logo on proposals list

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#680]
![Lark20210811-114036](https://user-images.githubusercontent.com/2264908/128966060-43c758f6-6952-42c7-adfa-0eca66894dbb.png)

**Comment by Popoulosss** [comment]
files
[icons-logo-project-opensquare.zip](https://github.com/opensquare-network/dotreasury/files/6967166/icons-logo-project-opensquare.zip)

preview
![image](https://user-images.githubusercontent.com/59445675/129003574-d781e17f-a73f-415b-a2aa-7661ce7295c7.png)
