### ISSUE TITLE
Misspelling in Burn

### ISSUE THREAD

**Issue by ccris02** [opensquare-network/dotreasury#709]
https://www.dotreasury.com/dot/burnt

If you highlight the Burnt graph it tells you how much was Burn but it says "Brunt" should that say "Burned".

**Comment by wliyongfeng** [comment]
@ccris02 https://www.merriam-webster.com/words-at-play/is-burnt-acceptable-as-the-past-tense-of-burn

Either seems acceptable, but 'burned' is better?

**Comment by ccris02** [comment]
Yes either Burnt or Burned would work. But Brunt wouldn't work here https://www.merriam-webster.com/dictionary/brunt
![Screenshot_20210915-060939](https://user-images.githubusercontent.com/66147586/133439512-43ac30e1-7caf-4a56-bc03-c483e48564a3.png)

**Comment by wliyongfeng** [comment]
Oh, our bad. Fixed and many thanks.
