### ISSUE TITLE
Council Voting

### ISSUE THREAD

**Issue by ccris02** [opensquare-network/dotreasury#710]
Would it be possible to create Council Dashboard to display council votes?

For example there are 19 Council member on Kusama and 10 votes are required for TIP to go through but usually takes few weeks to get all the votes so 9 of the Council doesn't vote.

**Comment by wliyongfeng** [comment]
@ccris02 Actually we have some plans to show the councilors' activities, like:
- motion voting attendance
- tip call statistics

But the priority is not high. Will do it in sometime later.

**Comment by wliyongfeng** [comment]
Check [here](https://www.dotreasury.com/ksm/users/GLVeryFRbg5hEKvQZcAnLvXZEXhiYaBjzSDwrXBXrfPF7wj/councilor) for the implementation.

**Comment by ccris02** [comment]
That looks awesome 😎
