### ISSUE TITLE
Separate the voting submission and IPFS uploading process

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#717]
- First we verify and save the voting data to database
- Run a background script which upload the not in IPFS data to IPFS
- In fronted, if data is not stored in IPFS, show a DB icon @Popoulosss

**Comment by Popoulosss** [comment]
- IPFS icon disabled if data is not stored

preview
![image](https://user-images.githubusercontent.com/59445675/134281507-4d82fdc4-f009-4308-8567-64671d6c3709.png)
