### ISSUE TITLE
As a user, I want to get the content of a proposal quickly when open the list

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#737]
Problems:
- Now we only have the links, beneficiary and proposer of the proposal, but users can still not know the proposal content.

Solutions:
- Add a short description column which describe what the proposal will do
- Merge index and propose time into one column to save space
- Maybe merge beneficiary and proposer to one column

**Comment by Popoulosss** [comment]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5

figma link
https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=1371%3A15826

preview
![image](https://user-images.githubusercontent.com/59445675/139642264-d048d284-1ad8-446e-908f-c4b236a5511c.png)
