### ISSUE TITLE
Tag proposals

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#738]
There will be different types of tags.

### Proposal type:
- Development
- Event
- Maintenance

### Status:
- Working
- Review
- Delivered

**Comment by Popoulosss** [comment]
- [ ] Combine description and tag
- [ ] Show status after tag

figma link
https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=1371%3A15826

preview
![image](https://user-images.githubusercontent.com/59445675/139774338-40181774-74f2-442a-b383-57c6b39d6c7f.png)

**Comment by wliyongfeng** [comment]
@YoshiyukiSakura will be the master of this issue

**Comment by YoshiyukiSakura** [comment]
implemention done, ready to review
