### ISSUE TITLE
fix bounties

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/dotreasury#850]
- [x] bgc

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/19513289/170672524-6f4f57e2-9e72-41b1-b29b-d40522cd8811.png">

- [x] show nav link

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/19513289/170672600-8252f8aa-959a-4b3f-8519-0546f3a800a6.png">

**Comment by YoshiyukiSakura** [comment]
- [ ] add link

https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2310%3A23526

<img width="556" alt="image" src="https://user-images.githubusercontent.com/12393771/170676608-5b8464a6-95bd-4067-b9b4-f8324a17f0ce.png">
