### ISSUE TITLE
Add links column for tips

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#898]
Show subsquare and polkassembly link as default.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2029%3A18484)

Preview
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/59445675/180165715-f9c9f0c2-8978-4ab2-b131-ca5a2de497d6.png">

**Comment by YoshiyukiSakura** [comment]
also recognize links for bounties
