### ISSUE TITLE
Curator should can be switched to beneficiary on bounties/child bounties table

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#902]
Clicking following table header will toggle curator and beneficiary.

![QEmPWfIXYk](https://user-images.githubusercontent.com/2264908/182133476-2cda2f1c-691d-49e7-b1ea-5327e251f73f.jpg)

**Comment by Popoulosss** [comment]
- Change table header font style `font-weight: 500; color: rgba(0, 0, 0, 0.65);`
- Clicking following table header will toggle curator and beneficiary
- Implement to bounties and child bounties

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/182278543-183d543f-883c-4104-a61c-f7605cafca04.png">

**Comment by Popoulosss** [comment]
- The table header changes should be applied to the table of the proposals

[Figma link](https://www.dotreasury.com/ksm/proposals)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/182278802-11fae9ae-fa69-46e5-aaea-dc5209b4b423.png">
