### ISSUE TITLE
As a user, I want to see the treasury workflow throw democracy

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#903]
We should show the referendum info in the timeline if it's for approving for rejecting treasury proposals.

**Comment by Popoulosss** [comment]
- [ ] Display referenda result to timeline, refer to [SubSquare](https://polkadot.subsquare.io/democracy/referendum/71)

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2780%3A20884)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/183018190-eb15ebca-7b60-4f9a-8376-592508b6d4b2.png">

**Comment by Popoulosss** [comment]
- [ ] Add a icon which links to subsquare
- [ ] Tag links to subsquare

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/183018675-5fb99d50-66bd-480d-98f9-d3ee9fce192a.png">

**Comment by Popoulosss** [comment]
- [ ] Implement loading state
- [ ] Implement error(unable to load the data) state

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2838%3A27600)

Files
[loading-animation icon.zip](https://github.com/opensquare-network/dotreasury/files/9355633/loading-animation.icon.zip)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/185015254-6e3c98cc-fbbe-49ef-b885-5c79725a5125.png">
