### ISSUE TITLE
As a beneficiary, I want to claim child bounty rewards from doTreasury

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/dotreasury#915]
[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2829%3A25902)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/186891080-047010e3-c44b-4817-a280-1962940afbea.png">

**Comment by Popoulosss** [comment]
Files
[loading-animation icon.zip](https://github.com/opensquare-network/dotreasury/files/9355686/loading-animation.icon.zip)

**Comment by 2nthony** [comment]
<img width="125" alt="image" src="https://user-images.githubusercontent.com/19513289/185827427-0b4aa89c-17a3-4667-8210-081730892ffb.png">

gap (unlock height - current height) if current > unlock, display 0, else unlock - current
unlock height / current height

**Comment by 2nthony** [comment]
<img width="24" alt="image" src="https://user-images.githubusercontent.com/19513289/185828066-9b5e9d75-8134-4477-bb91-0808f46a18cc.png">

倒计时的分子和分母：
分子：现在还剩多少时间
分母： unlock高度 - award 动作的高度

**Comment by Popoulosss** [comment]
Updated

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=3637%3A28181)
