### ISSUE TITLE
Add countdown component for bounty/child bounty pending payout status

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#918]
It's a child issue of #915 . We implement the countdown component first. The claim button and actions will be implemented after the connecting wallet features are done.

[Figma](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2829%3A25902)

**Comment by 2nthony** [comment]
design tracking: https://github.com/opensquare-network/ui/issues/48
