### ISSUE TITLE
As a user, I want to see all the ranked proposal beneficiaries

### ISSUE THREAD

**Issue by wliyongfeng** [opensquare-network/dotreasury#919]
Currently we have top 11 proposal beneficiaries, but that's not enough, I want to see the list contains all the Beneficiaries, ranked by the estimated fiat value.

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2968%3A21318)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/186113847-99596a15-1e1a-4d9a-9a1c-7fccd6b33522.png">
