### ISSUE TITLE
Connect with polkadot.js extensioin/subwallet/talisman, and support nova wallet.

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#921]
- [x] Add connect button to header menu bar
- [x] Implement extension selector
- [x] Implement address selector
- [x] Make sure correctly handling ETH accounts
- [x] ~~Add Nova extension support~~ (Same as polkadot-js)
- [x] Logout (@Popoulosss )
- [x] Loading effect (@Popoulosss )
- [x] Save extension to localStorage

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2677%3A22492)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/186808891-7e83c292-2d17-42ba-8d72-48e011f7ef73.png">

**Comment by Popoulosss** [comment]
Files
[dot-loading-grey.svg.zip](https://github.com/opensquare-network/dotreasury/files/9429399/dot-loading-grey.svg.zip)
