### ISSUE TITLE
Remove comments feature. Redirect users to subsquare if they want to.

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#922]
- [ ] UI Design (@Popoulosss )
- [ ] Implement

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2729%3A23194)

Preview
Empty state
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/186639377-790e0cba-3d1a-4ac7-9d0c-178394ed120e.png">
Keep the original comments
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/186639481-43da24eb-6814-4663-919a-403c515888d7.png">
