### ISSUE TITLE
Erroneous links

### ISSUE THREAD

**Issue by dot-alert** [opensquare-network/dotreasury#947]
Hello,

Just letting you know that DotTreasury's entries are not linking to the correct Polkassembly platform.
The link for Kusama **TIPS** proposals redirect users to Polkadot's Polkassembly items. See below 👇🏿

![DotTreasuryerror](https://user-images.githubusercontent.com/112253893/187740721-11e5fbe3-f26a-4d5c-9793-b488a3f94496.JPG)

Cheers.

**Comment by wliyongfeng** [comment]
Thanks a lot, fixed.
