### ISSUE TITLE
page users detail table filter

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/dotreasury#984]
Current solution: disable this feature.

reproduce:

- proposals set a filter value
- switch to tips tab, also fetch the table data with wrong status

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/19513289/190591736-d8100e89-ed96-4f3f-90af-e9da75a07c4f.png">

**Comment by wliyongfeng** [comment]
Currently we don't need this.
