### ISSUE TITLE
Implement council tip action support

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#989]
Add tip action button to tip detail page, councilors can call to set tip value.

- [x] Tip UI design (@Popoulosss )
- [x] Implement

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=3917%3A23687)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/192446192-30eaa083-ec2e-4542-a0b3-b6d476c51b3d.png">
