### ISSUE TITLE
Implement newTip/reportAwesome support

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#990]
Implement newTip/reportAwesome support

https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=2698%3A20892

![image](https://user-images.githubusercontent.com/6297057/191238543-9677cb7e-c3ca-4b6a-8606-5b83b6981a6b.png)

**Comment by Popoulosss** [comment]
Updated

Add error message

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/191649613-d522e511-7fe3-45b0-a41c-456b7084b720.png">

**Comment by Popoulosss** [comment]
- [ ] New tip popup display in mobile

[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=3797%3A26814&viewport=754%2C-338%2C0.16)

Preview
<img width="320" alt="image" src="https://user-images.githubusercontent.com/59445675/191649936-30fb31fd-a14e-4738-a7b4-8dbe060201a3.png">

**Comment by Popoulosss** [comment]
- [ ] Display 'Councilor' tag

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/191650066-61efa99e-8ffb-4f6a-a551-638edac1031f.png">
