### ISSUE TITLE
Implement Retract tip support

### ISSUE THREAD

**Issue by hyifeng** [opensquare-network/dotreasury#991]
Add Retract tip button to tip detail page

- [x] Retract Tip UI Design (@Popoulosss )
- [x] Implement

**Comment by Popoulosss** [comment]
[Figma link](https://www.figma.com/file/cIcOZxD9Ctqdj4xc9Xoctm/doTreasury?node-id=3917%3A23687)

Preview
<img width="640" alt="image" src="https://user-images.githubusercontent.com/59445675/192446202-38ae8a90-3a40-4020-b221-0178b86eb05f.png">
